server:
  port: 8081
  servlet:
    session:
      timeout: 10
logging:
  level:
    com.lkl: debug
person:
  age: 18
  name: likelong
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
